# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RandomUserList' do
  use_frameworks!
  pod 'Alamofire'
  pod 'SDWebImage', '~> 4.0'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  # Pods for RandomUserList

  target 'RandomUserListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RandomUserListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
